name: Release Extension

on:
  push:
    tags:
      - "v*" # 当推送带 v 前缀的标签时触发，如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package Extension
        run: npm run package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 
